# app/server/models/interview_feedback.py

from pydantic import BaseModel, Field


class Recommendation(BaseModel):
    """
    Actionable recommendation for interview improvement.
    """

    category: str = Field(
        description=(
            "Category of the recommendation."

            "Examples:"

            "- communication"
            "- ownership"
            "- problem_solving"
            "- impact"
            "- domain_expertise"
        )
    )

    priority: str = Field(
        description=(
            "Priority level."

            "Expected values:"

            "- high"
            "- medium"
            "- low"
        )
    )

    recommendation: str = Field(
        description="Specific actionable recommendation."
    )


class LLMInterviewFeedback(BaseModel):
    """
    Human-readable interview feedback generated by the LLM.
    """

    summary: str = Field(
        description="Overall interview summary."
    )

    strengths: list[str] = Field(
        default_factory=list,
        description="Key strengths demonstrated by the candidate."
    )

    weaknesses: list[str] = Field(
        default_factory=list,
        description="Key weaknesses or improvement opportunities."
    )

    recommendations: list[
        Recommendation
    ] = Field(
        default_factory=list,
        description="Actionable recommendations."
    )