# app/server/llm/contracts/prompt_outputs.py

from typing import Generic, TypeVar

from pydantic import BaseModel, Field

from app.server.models.interview_feedback import LLMInterviewFeedback

T = TypeVar("T")


# ============================================================
# Token Usage
# ============================================================

class TokenUsage(BaseModel):
    """
    Token consumption reported by an LLM provider.

    These metrics are provider-agnostic and are intended
    for:

    - Cost tracking
    - Usage analytics
    - Performance monitoring
    - Capacity planning

    Not all providers expose token usage information.
    Missing values should default to zero or be omitted.
    """

    prompt_tokens: int = Field(
        default=0,
        description=(
            "Number of input tokens consumed by "
            "the prompt."
        )
    )

    completion_tokens: int = Field(
        default=0,
        description=(
            "Number of output tokens generated "
            "by the model."
        )
    )

    total_tokens: int = Field(
        default=0,
        description=(
            "Total tokens consumed by the request."
        )
    )

# ============================================================
# Generic LLM Response
# ============================================================

class LLMResponse(BaseModel, Generic[T]):
    """
    Standardized structured response returned by an LLM.

    All prompt outputs may optionally be wrapped by this
    model to support future metadata expansion such as:

    - confidence
    - reasoning
    - provider information
    - token usage
    """

    result: T = Field(
        description="Structured result generated by the model."
    )

    token_usage: TokenUsage | None = Field(
        default=None,
        description="Token usage reported by the provider."
    )


# ============================================================
# Intro Phase Outputs
# ============================================================

class EducationContext(BaseModel):
    """
    Educational background highlighted by the candidate
    during the self-introduction phase.
    """

    institution: str = Field(
        description="School, university, bootcamp, or educational institution."
    )

    program: str | None = Field(
        default=None,
        description="Program, major, degree, or field of study."
    )

    status: str | None = Field(
        default=None,
        description=(
            "Current academic status such as "
            "'current student', 'graduated', "
            "'phd candidate', etc."
        )
    )


class HighlightedExperience(BaseModel):
    """
    Experience intentionally emphasized by the candidate
    during self-introduction.

    These experiences are later used for experience
    selection and deep-dive questioning.
    """

    organization: str | None = Field(
        default=None,
        description=(
            "Company, research lab, startup, school, "
            "or organization."
        )
    )

    timeframe: str | None = Field(
        default=None,
        description="Time period associated with the experience."
    )

    summary: str = Field(
        description="One-sentence summary of the experience."
    )

    responsibilities: list[str] = Field(
        default_factory=list,
        description="Responsibilities mentioned by the candidate."
    )

    achievements: list[str] = Field(
        default_factory=list,
        description="Achievements or impact mentioned by the candidate."
    )


class IntroExtractionResult(BaseModel):
    """
    Structured candidate context extracted from the
    self-introduction phase.

    This output is used by downstream phases for:

    - Experience selection
    - Follow-up question generation
    - Evaluation context construction
    """

    most_recent_role: str | None = Field(
        default=None,
        description="Most recent or current professional role."
    )

    education: EducationContext | None = Field(
        default=None,
        description="Most relevant educational background."
    )

    highlighted_experiences: list[
        HighlightedExperience
    ] = Field(
        default_factory=list,
        description="Experiences highlighted by the candidate."
    )

    domain_keywords: list[str] = Field(
        default_factory=list,
        description=(
            "Top domain, industry, or technical keywords "
            "associated with the candidate."
        )
    )

    other_context: list[str] = Field(
        default_factory=list,
        description="Additional contextual information."
    )


# ============================================================
# Experience Phase Outputs
# ============================================================

class ExperienceExtractionResult(BaseModel):
    """
    Structured evidence extracted from an experience
    discussion.

    This output is used for:

    - Coverage tracking
    - Deep-dive questioning
    - Evaluation
    """

    experience_type: str | None = Field(
        default=None,
        description=(
            "Experience type such as internship, project, "
            "research, startup, or full-time role."
        )
    )

    experience_name: str | None = Field(
        default=None,
        description="Name of the experience being discussed."
    )

    what: str | None = Field(
        default=None,
        description="What the candidate worked on."
    )

    why: str | None = Field(
        default=None,
        description="Why the work was necessary."
    )

    how: str | None = Field(
        default=None,
        description=(
            "How the work was carried out, including "
            "implementation details and technologies."
        )
    )

    challenge: str | None = Field(
        default=None,
        description="Major challenge encountered."
    )

    outcome: str | None = Field(
        default=None,
        description="Result, impact, or measurable outcome."
    )


# ============================================================
# Question Generation Outputs
# ============================================================

class QuestionGenerationResult(BaseModel):
    """
    Structured question generation output.

    Returned by intro, experience, and deep-dive
    question generation prompts.
    """

    question: str = Field(
        description="Question to ask the candidate."
    )

    phase: str = Field(
        description="Interview phase associated with the question."
    )

    target_fields: list[str] = Field(
        default_factory=list,
        description=(
            "Coverage fields this question intends "
            "to collect."
        )
    )


# ============================================================
# Evaluation Outputs
# ============================================================

class DimensionScore(BaseModel):
    """
    Evaluation result for a single competency dimension.
    """

    name: str = Field(
        description="Name of the evaluated dimension."
    )

    score: float = Field(
        ge=0,
        le=100,
        description="Score assigned to the dimension."
    )

    justification: str = Field(
        description="Reasoning behind the assigned score."
    )


class PhaseEvaluationResult(BaseModel):
    """
    Evaluation result for a single interview phase.
    """

    phase_name: str = Field(
        description="Name of the evaluated phase."
    )

    dimensions: list[
        DimensionScore
    ] = Field(
        description="Scores for all evaluated dimensions."
    )

    overall_score: float = Field(
        ge=0,
        le=100,
        description="Aggregated phase score."
    )

    strengths: list[str] = Field(
        default_factory=list,
        description="Notable strengths."
    )

    improvements: list[str] = Field(
        default_factory=list,
        description="Improvement opportunities."
    )


# class InterviewEvaluationResult(BaseModel):
#     """
#     Final evaluation result for the entire interview.
#     """
#
#     phase_results: list[
#         PhaseEvaluationResult
#     ] = Field(
#         description="Results for all interview phases."
#     )
#
#     communication_score: float = Field(
#         ge=0,
#         le=100,
#         description="Overall communication score."
#     )
#
#     professional_score: float = Field(
#         ge=0,
#         le=100,
#         description="Overall professional competency score."
#     )
#
#     overall_score: float = Field(
#         ge=0,
#         le=100,
#         description="Final interview score."
#     )
#
#     assessment_confidence: float = Field(
#         ge=0,
#         le=1,
#         description="Confidence level of the assessment."
#     )
#
#     strengths: list[str] = Field(
#         default_factory=list,
#         description="Overall strengths identified."
#     )
#
#     improvements: list[str] = Field(
#         default_factory=list,
#         description="Overall improvement opportunities identified."
#     )
#
#     llm_feedback: LLMInterviewFeedback | None = Field(
#         default=None,
#         description="Human-readable final interview feedback."
#     )

class InterviewFeedbackResult(BaseModel):
    """
    Human-readable final interview feedback.

    Generated after all scores have already
    been computed by the EvaluationEngine.
    """

    assessment_confidence: float = Field(
        ge=0,
        le=1,
    )

    llm_feedback: LLMInterviewFeedback

class ResumeReviewResult(BaseModel):
    """
    Result returned by the resume ownership / update decision step.

    This is used before overwriting an existing candidate resume.

    Rules:
    - If `is_same_candidate` is False, keep the old resume untouched.
    - If `is_same_candidate` is True, proceed with resume normalization
      and update the existing resume record.
    """

    is_same_candidate: bool = Field(
        description=(
            "Whether the pasted resume belongs to the same candidate "
            "as the existing record."
        )
    )

    confidence: float = Field(
        ge=0,
        le=1,
        default=0.0,
        description=(
            "Confidence that the decision is correct."
        ),
    )

    reason: str = Field(
        default="",
        description=(
            "Short reason for the ownership decision."
        ),
    )

class TurnAssessmentResult(BaseModel):
    relevance: float = Field(
        ge=0,
        le=1,
        description="How directly the answer addresses the question."
    )

    clarity: float = Field(
        ge=0,
        le=1,
        description="How clearly and coherently the answer is expressed."
    )

    fluency: float = Field(
        ge=0,
        le=1,
        description="How smooth, natural, and readable the answer is."
    )

    confidence: float = Field(
        ge=0,
        le=1,
        description="How confident the model is in this assessment."
    )